version: '3'

services:
  nodejs:
    image: diegodi123/cutbarbershop-dockerizado-develop:latest
    build: .
    depends_on:
      - db
    networks:
      - connection
    ports:
      - 3334:3334
  db:
    image: postgres:13.2-alpine
    ports:
      - 5433:5433
    volumes:
      - ./data_postgres:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_PASSWORD: docker
    networks:
      - connection
networks:
  connection:
    driver: bridge
