version: '3'

services:
  nodejs:
    image: diegodi123/cutbarbershop-dockerizado-production:latest
    build: .
    depends_on:
      - db
    networks:
      - connection
    ports:
      - 3331:3331
  db:
    image: postgres:13.2-alpine
    ports:
      - 5431:5431
    volumes:
      - ./data_postgres:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_PASSWORD: docker
    networks:
      - connection
networks:
  connection:
    driver: bridge
